spring:
  application:
    name: management
  datasource:
    url: jdbc:postgresql://localhost:5432/book_management
    username: book
    password: management
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug